apiVersion: v1
kind: Secret
metadata:
  name: designate-rndc-key
stringData:
  rndc.key: |
    key "rndc-key" {
        algorithm hmac-sha256;
        # Replace with rndc secret key
        secret "${RNDC_SECRET_KEY}";
    };
