---
images:
  tags:
    ceph_config_helper: 'quay.io/airshipit/ceph-config-helper:ubuntu_jammy_20.2.1-1-20260407'
conf:
  ceph:
    global:
      # TODO: Get mon host from rook-ceph-mon-endpoints configmap
      mon_host: "will be discovered"
      # The number of Ceph monitor endpoints to wait for before adding the ConfigMap
      mon_count: 1
