---
images:
  tags:
    test: docker.io/xrally/xrally-openstack:2.0.0
    bootstrap: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble-20260609
    db_init: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble-20260609
    heat_db_sync: quay.io/airshipit/heat:2026.1-ubuntu_noble
    db_drop: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble-20260609
    rabbit_init: docker.io/rabbitmq:3.13-management
    ks_user: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble-20260609
    ks_service: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble-20260609
    ks_endpoints: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble-20260609
    heat_api: quay.io/airshipit/heat:2026.1-ubuntu_noble
    heat_cfn: quay.io/airshipit/heat:2026.1-ubuntu_noble
    heat_engine: quay.io/airshipit/heat:2026.1-ubuntu_noble
    heat_engine_cleaner: quay.io/airshipit/heat:2026.1-ubuntu_noble
    heat_purge_deleted: quay.io/airshipit/heat:2026.1-ubuntu_noble
    dep_check: quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble
    image_repo_sync: docker.io/docker:17.07.0
