images:
  tags:
    libvirt: quay.io/airshipit/libvirt:2026.1-ubuntu_noble
    ceph_config_helper: 'quay.io/airshipit/ceph-config-helper:ubuntu_jammy_20.2.1-1-20260407'
    dep_check: quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_noble
    image_repo_sync: quay.io/airshipit/docker:27.5.0
    kubectl: docker.io/bitnami/kubectl:latest

conf:
  qemu:
    vnc_tls: "0"
    vnc_tls_x509_verify: "0"
    stdio_handler: "file"
    user: "nova"
    group: "kvm"
    systemd_controllers: []
